import 'styles/globals.css'
import Header from '../components/Header'
import Footer from '../components/Footer';
import Image from 'next/image';
export const metadata = {
  title: 'Burbujitas & Bling',
  description: 'Generated by Next.js', //todo
}

export default function RootLayout({children,}: {children: React.ReactNode}) {
  return (
    <html lang="en" className='bg-softPink'>
      <body>
       <div className="flex items-center justify-center min-h-screen">
      <Image
        src="https://drive.google.com/uc?export=view&id=1-nqchyAiZgCh4HJL3-YTe-LwHeLojwef"
        alt="Your image description"
        width={800}
        height={800}
        className="rounded-lg"
         priority 
      />
    </div>
    </body>
    </html>
  );
}
