import "../styles/globals.css";
import Header from "../components/Body/Header";
import Footer from "../components/Body/Footer";

export const metadata = {
  title: "Burbujitas & Bling",
  description: "Generated by Next.js", //todo
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="bg-softPink md:text-md text:sm text-softBrown">
      <body className="flex flex-col min-h-screen">
        <Header />

        {/* main content grows to fill remaining space */}
        <main className="flex-grow w-full">{children}</main>

        {/* footer naturally at bottom */}
        <Footer />
      </body>
    </html>
  );
}
